# -*- coding: utf-8 -*-
{
    'name': "BS CRM Customization",
    'summary': """""",
    'description': """
    """,
    'author': "Amine Trifi",
    'website': "https://barrettestructural.com/",

    'category': '',
    'version': '17.0',
    'depends': ['hr', 'sale_crm', 'sales_team', 'l10n_ca', 'project', 'sale_management', 'base_address_extended', 'website_partner', 'base_vat', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/hide_sale_module.xml',
        'data/cron_validity_date.xml',
        'data/server_actions.xml',
        #'data/sale_order_stage_data.xml',
        'data/close_reason.xml',
        'data/contact_type.xml',
        'data/mail_templates.xml',
        'data/mail_notification_layout.xml',
        'report/report_saleorder_document.xml',
        'views/contact_type_views.xml',
        'views/mail_activity_views.xml',
        'views/contact_role_views.xml',
        'views/contact_views.xml',
        'views/res_partner_views.xml',
        'views/search_views.xml',
        'views/customer_category_views.xml',
        'views/crm_lead_views.xml',
        'views/res_partner_view_team.xml',
        'views/partner_closure_reason_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_views.xml',
        'views/order_line_views.xml',
        'views/sale_order_portal_content.xml',
        'views/city_views.xml',
        'views/mail_templates.xml',
        'wizard/partner_closure_reason_wizard.xml',
        'wizard/partner_bloque_views.xml',
        'wizard/contact_categorization_wizard.xml',
        'wizard/mail_compose_wizard_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'bsi_crm_custom/static/src/js/mfiles_pdf_preview.js',
            'bsi_crm_custom/static/src/js/company_service_patch.js',
            'bsi_crm_custom/static/src/js/activity_menu.js',
        ],
    },
    'installable': True,
    'auto_install': False,
}
